### ISSUE TITLE
Help with example

### ISSUE THREAD

**Issue by ghost** [rbiggs/chuki#1]
Hi,

I'm trying to play with your code but I get an error on the following part:

```
// Define callbacks for events.
  logHello() {
    title.innerHTML = `Hello ${document.getElementById('hello').value}!`
  }
```

<code>title is not defined</code>.

Can you help me ?

**Comment by rbiggs** [comment]
Hmm... You need to have a reference to the title. I don't see one, neither will the browser, hence the error 'undefined'. You need to do something like:
```javascript
// Define callbacks for events.
  logHello() {
     var title = document.querySelector('#title')
     title.innerHTML = `Hello ${document.getElementById('hello').value}!`
  }
```
That's assuming you have a title with an id of "title". Follow me?

**Comment by rbiggs** [comment]
I suggest you take a look at my other library, Composi. Chuki was a lot of experiments that eventually led to the development of Composi: https://composor.github.io

**Comment by rbiggs** [comment]
I've updated the example in the README so that it works. I also added some links to live Codepen examples.

**Comment by ghost** [comment]
Thanks a lot.
I'll have a look to composor.
